# 线上配置文件
# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ***
    username:  ***
    password:  ***
  redis:
    port:  ***
    host:  ***
    password:  ***
    database:  ***
server:
  address:  ***
  port:  ***
  servlet:
    context-path:  ***
    session:
      cookie:
        domain:  ***
        same-site: lax
        secure: false
        http-only: true



