spring:
  application:
    name: yupao-backend-master
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:  ***
    username:  ***
    password:  ***
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    port:  ***
    host:  ***
    password:  ***
    database:  ***
  session:
    timeout:  ***
    storeType: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-Zone: Asia/Shanghai
server:
  port:  ***
  servlet:
    context-path:  ***
    session:
      cookie:
        domain:  ***
        same-site: lax
        secure: false
        http-only: true



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



